apiVersion: v1
kind: Service
metadata:
  name: quorum
  labels:
    app: quorum
spec:
  # type: NodePort
  clusterIP: None
  ports:
  - port: 8454
    name: p2p
  - port: 9000
    name: rpc
  selector:
    app: quorum
